spring:
  application:
    name: OrderService

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.intern.orderservice.dto.payment.PaymentResponse
        spring.deserializer.value.error.handler.behavior: log
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    dead-letter-topic: ${spring.application.name}-DLT

  liquibase:
    change-log: classpath:db/changelog/master.yaml

server:
  port: 8082

userservice:
  baseurl: ${USERSERVICE_BASEURL}
  endpoint:
    users: "/api/users/"
    search-email: "/api/users/search?email="

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
    logging:
      export:
        enabled: true
      endpoint: "http://localhost:4318/v1/logs"
    tracing:
      export:
        enabled: true
      endpoint: "http://localhost:4318/v1/traces"
  observations:
    key-values:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.intern.orderservice: DEBUG